### PR TITLE
Email Preview and Editor

### PR DESCRIPTION
**Pull request by Vardaan-02**
Issue: #25

I tried my best to make it look good, but the color scheme turned out to be bad. I wasted 15 minutes on it.

The page is fully responsive and animated using Framer Motion and Tailwind CSS.

It automatically detects the placeholders and creates fields for them to be edited.

I hope fetching the template wasn't part of my task.

I had to create some components for a modular design, and I hope that's acceptable.

Thank you, mentor, for providing me with this task.

Screenshot From 2024-12-17 23-34-38

### CODE REVIEW

**Comment by ANJALIJAISWAL4213** [comment]
You can't give such titles to pr request

**Comment by Vardaan-02** [comment]
Should I change this make a request again ?

**Comment by ANJALIJAISWAL4213** [comment]
Yes

**Comment by Vardaan-02** [comment]
Changed the title

**Pull request merged**
